events {}

http {

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    upstream command_service {
        server command-service:8000;
    }

    upstream query_service {
        server query-service:8001;
    }

    server {
        listen 80;

        location /command/ {
            limit_req zone=api_limit burst=10;
            proxy_pass http://command_service/;
        }

        location /query/ {
            limit_req zone=api_limit burst=10;
            proxy_pass http://query_service/;
        }
    }
}